import { Component } from '@angular/core';
import { FormBuilder, FormGroup, ReactiveFormsModule } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatIconModule } from '@angular/material/icon';
import { MatSelectModule } from '@angular/material/select';

@Component({
  selector: 'app-data-copilot',
  standalone: true,
  imports: [MatSelectModule,MatButtonModule, MatCardModule, MatIconModule, ReactiveFormsModule],
  templateUrl: './data-copilot.component.html',
  styleUrl: './data-copilot.component.scss'
})
export class DataCopilotComponent {

  // TODO:: Get Edition from Api
  editions = ['local', 'staging', 'live'];
  editionForm: FormGroup;

  constructor(private fb: FormBuilder) { }

  ngOnInit(): void {
    this.editionForm = this.fb.group({
      edition: ['']
    });
  }

  autoGeneratedCode(){
    console.log(this.editionForm.value.edition)
  }

}
