import { HttpClient } from '@angular/common/http';
import { Component } from '@angular/core';
import { FormBuilder, FormGroup, ReactiveFormsModule } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatIconModule } from '@angular/material/icon';
import { MatSelectModule } from '@angular/material/select';
import { Context as DnnContext } from '@2sic.com/sxc-angular';
import { Context } from '../../shared/services/context';
import { map } from 'rxjs';
import { CommonModule } from '@angular/common';
interface EditionData {
  editions: Edition[];
  isConfigured: boolean;
}
interface Edition {
  name: string;
  description: string;
}

@Component({
  selector: 'app-data-copilot',
  standalone: true,
  imports: [MatSelectModule, MatButtonModule, MatCardModule, MatIconModule, ReactiveFormsModule, CommonModule],
  templateUrl: './data-copilot.component.html',
  styleUrl: './data-copilot.component.scss'
})
export class DataCopilotComponent {

  editions: string[] = [];
  editionForm: FormGroup;
  webApiEdiotions: string = 'admin/code/geteditions';
  webApiGeneratedCode: string = 'admin/code/generateDataModels';
  editions$ = this.getEditionsFromApi();

  constructor(private fb: FormBuilder, private http: HttpClient, private dnnContext: DnnContext, private context: Context,) { }

  ngOnInit(): void {
    this.editionForm = this.fb.group({
      edition: ['']
    });
  }


  getEditionsFromApi() {
    return this.http.get<EditionData[]>(this.dnnContext.$2sxc.http.apiUrl(this.webApiEdiotions), {
      params: {
        appId: this.context.appId.toString()
      }
    }).pipe(
      map((editions:any) => {
        return editions.editions.map((d:Edition) => d.name);
      })
    );
  }

  autoGeneratedCode() {
    // console.log(this.editionForm.value.edition)
   this.http.get<any[]>(this.dnnContext.$2sxc.http.apiUrl(this.webApiGeneratedCode), {
      params: {
        appId: this.context.appId.toString(),
        edition: this.editionForm.value.edition
      }
    }).subscribe(d => console.log(d));
  }

}
