// apps management
export const APPS_MANAGEMENT_DIALOG = 'APPS_MANAGEMENT_DIALOG';
export const IMPORT_APP_DIALOG = 'IMPORT_APP_DIALOG';
export const ENABLE_LANGUAGES_DIALOG = 'ENABLE_LANGUAGES_DIALOG';

// app administration
export const APP_ADMINISTRATION_DIALOG = 'APP_ADMINISTRATION_DIALOG';
export const ADD_CONTENT_TYPE_DIALOG = 'ADD_CONTENT_TYPE_DIALOG';
export const EDIT_CONTENT_TYPE_DIALOG = 'EDIT_CONTENT_TYPE_DIALOG';
export const EDIT_FIELDS_DIALOG = 'EDIT_FIELDS_DIALOG';
export const CONTENT_TYPES_FIELDS_ADD_DIALOG = 'CONTENT_TYPES_FIELDS_ADD_DIALOG';
export const EXPORT_CONTENT_TYPE_DIALOG = 'EXPORT_CONTENT_TYPE_DIALOG';
export const IMPORT_CONTENT_TYPE_DIALOG = 'IMPORT_CONTENT_TYPE_DIALOG';
export const SET_PERMISSIONS_DIALOG = 'SET_PERMISSIONS_DIALOG';

// code editor
export const CODE_EDITOR_DIALOG = 'CODE_EDITOR_DIALOG';
