// apps management
export const APPS_MANAGEMENT_DIALOG = 'APPS_MANAGEMENT_DIALOG';
export const IMPORT_APP_DIALOG = 'IMPORT_APP_DIALOG';

// app administration
export const APP_ADMINISTRATION_DIALOG = 'APP_ADMINISTRATION_DIALOG';
export const CONTENT_ITEMS_DIALOG = 'CONTENT_ITEMS_DIALOG';
export const IMPORT_CONTENT_ITEM_DIALOG = 'IMPORT_CONTENT_ITEM_DIALOG';
export const EDIT_CONTENT_TYPE_DIALOG = 'EDIT_CONTENT_TYPE_DIALOG';
export const CONTENT_TYPE_FIELDS_DIALOG = 'CONTENT_TYPE_FIELDS_DIALOG';
export const EDIT_CONTENT_TYPE_FIELDS_DIALOG = 'EDIT_CONTENT_TYPE_FIELDS_DIALOG';
export const EXPORT_CONTENT_TYPE_DIALOG = 'EXPORT_CONTENT_TYPE_DIALOG';
export const IMPORT_CONTENT_TYPE_DIALOG = 'IMPORT_CONTENT_TYPE_DIALOG';
export const SET_PERMISSIONS_DIALOG = 'SET_PERMISSIONS_DIALOG';
export const IMPORT_QUERY_DIALOG = 'IMPORT_QUERY_DIALOG';
export const EXPORT_APP_ALL = 'EXPORT_APP_ALL';
export const EXPORT_APP_PARTS = 'EXPORT_APP_PARTS';
export const IMPORT_APP_PARTS = 'IMPORT_APP_PARTS';

// code editor
export const CODE_EDITOR_DIALOG = 'CODE_EDITOR_DIALOG';

// edit-ui
export const ITEMS_EDIT_DIALOG = 'ITEMS_EDIT_DIALOG';
