import { CommonModule } from '@angular/common';
import { HttpClient } from '@angular/common/http';
import { Component, input, signal } from '@angular/core';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatIconModule } from '@angular/material/icon';
import { MatSelectModule } from '@angular/material/select';
import { MatSnackBar } from '@angular/material/snack-bar';
import { Router } from '@angular/router';
import { EntityLightIdentifier } from 'projects/edit-types/src/EntityLight';
import { map, Observable, of, take } from 'rxjs';
import { transient } from '../../../../../core';
import { DialogRoutingState } from '../../edit/dialog/dialogRouteState.model';
import { convertFormToUrl } from '../../shared/helpers/url-prep.helper';
import { EditForm, EditPrep } from '../../shared/models/edit-form.model';
import { RichResult } from '../../shared/models/rich-result';
import { DialogRoutingService } from '../../shared/routing/dialog-routing.service';
import { Context } from '../../shared/services/context';
import { EntityService } from '../../shared/services/entity.service';
import { CopilotService } from './copilot-service';

type DataCopilotConfiguration = {
  id: string;
  title?: string;
  description?: string;
  created?: string;
  lastModified?: string;
};

@Component({
  selector: 'app-copilot-generator',
  templateUrl: './copilot-generator.component.html',
  styleUrls: ['./copilot-generator.component.scss'],
  imports: [
    MatSelectModule,
    MatButtonModule,
    MatCardModule,
    MatIconModule,
    CommonModule,
  ]
})
export class CopilotGeneratorComponent {

  outputType = input<string>();
  title? = input<string>('Copilot Generator');
  private copilotSvc = transient(CopilotService);
  private entitySvc = transient(EntityService);
  #dialogRouter = transient(DialogRoutingService);
  router = transient(Router);

  private readonly copilotConfigurationGuid = 'b08dcd23-2eb0-4a5e-a3d0-3178d2aae451';

  webApiGeneratedCode: string = 'admin/code/generateDataModels';
  editions$ = this.copilotSvc.getEditions();

  showConfigurationDropdown = signal(false);

  entities$: Observable<EntityLightIdentifier[]>;
  selectedEntity?: DataCopilotConfiguration;

  generators$ = this.copilotSvc.getGenerators()
    .pipe(
      map((gens) => gens.filter(g => g.outputType === this.outputType()))
    );

  selectedGenerator$ = this.generators$.pipe(map(gens => gens.find(g => g.name === this.selectedGenerator)));

  selectedGenerator = '';
  selectedEdition = '';

  constructor(
    private http: HttpClient,
    private context: Context,
    private snackBar: MatSnackBar,
  ) { }

  ngOnInit(): void {
    this.generators$.pipe(take(1)).subscribe(gens => {
      this.selectedGenerator = gens[0]?.name ?? '';
    });
    this.copilotSvc.specs.pipe(take(1)).subscribe(specs => {
      // this.selectedGenerator = specs.generators[0]?.name ?? '';
      this.selectedEdition = specs.editions.find(e => e.isDefault)?.name ?? '';
    });
    this.fetchEntities();
  }

  openSettings(config?: DataCopilotConfiguration) {
    const configurationContentType = this.copilotConfigurationGuid;
    // TODO: @2pp - ensure editing existing config works
    // Build overrideContents for existing configuration or new
    const overrideContents: Record<string, unknown>[] = [{ ...(config ?? {}) }];

    const subRoute = this.#routeAddItem(configurationContentType);
    const rawUrl = this.#urlTo(`edit/${subRoute}`);
    const normalized = rawUrl.replace(/^#\/?/, '').replace(/^\//, '');
    const routeSegments = normalized.split('/').filter(Boolean);

    this.router.navigate(routeSegments, {
      state: {
        returnValue: true,
        overrideContents
      } satisfies DialogRoutingState,
    });
  }

  fetchEntities() {
    this.entities$ = this.entitySvc.getEntities$(of({ contentTypeName: this.copilotConfigurationGuid }));
  }

  #routeAddItem(configurationContentType: string): string {
    // Only produce "new:GUID" without "edit/"
    return convertFormToUrl({
      items: [EditPrep.newFromType(configurationContentType)],
    } satisfies EditForm);
  }

  #urlTo(subRoute: string): string {
    return `#${this.#dialogRouter.urlSubRoute(subRoute)}`;
  }

  toggleConfigurationDropdown() {
    // Make the box longer & show the dropdown. Toggle show state.
    this.showConfigurationDropdown.set(!this.showConfigurationDropdown());
  }

  autoGeneratedCode() {
    this.http.get<RichResult>(this.webApiGeneratedCode, {
      params: {
        appId: this.context.appId.toString(),
        edition: this.selectedEdition,
        generator: this.selectedGenerator,
      }
    }).subscribe(d => {
      this.snackBar.open(d.message + `\n (this took ${d.timeTaken}ms)`, null, { duration: 5000, });
    });
  }
}
